site_name: USST_RSRCSharing

theme:
  name: "material"
  features:
  - navigation.footer
  - navigation.sections
  - announce.dismiss
  palette:
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: defalt
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: indigo
    accent: indigo
  language: zh
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github


nav:
- 课程指南:
  - 高等数学A: 课程指南/高等数学A.md

repo_url: https://github.com/ShowsOwO/USST_RSRCSharing
repo_name: USST_RSRCSharing

copyright: Copyright &copy; 2024 USST Opensource Organization

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css